"""Defines the graph state schema for the resume tailoring workflow.

The ResumeGraphState TypedDict acts as the shared state passed between
all nodes in the LangGraph workflow.
"""

from typing import Any, Dict, List, Optional, TypedDict


class ResumeGraphState(TypedDict):

    """LangGraph state representation for the resume tailoring workflow.

    Attributes:
        thread_id (str): Unique identifier for the current run/thread.
        job_description (str): Raw text of the target job description.
        resume_text (str): Raw text of the parsed existing resume.
        llm_provider (Optional[str]): Selected LLM provider name.
        template_path (Optional[str]): Path to uploaded document template if any.
        extracted_skills (Optional[List[str]]): Current candidate skills extracted from resume.
        suggested_skills (Optional[List[str]]): Recommended skills/keywords matching target JD.
        approved_skills (Optional[List[str]]): Final human-approved skills list.
        user_suggestions (Optional[str]): Custom instructions/feedback provided by human reviewer.
        planner_output (Optional[Dict[str, Any]]): Structuring plan generated by Planner.
        tailored_context (Optional[Dict[str, Any]]): Parameter dictionary passed to generate_resume.py.
        generated_resume_path (Optional[str]): Local filepath of compiled DOCX.
        generated_resume_filename (Optional[str]): Target output filename.
        ats_score_result (Optional[Dict[str, Any]]): ATS score breakdown and feedback.
        execution_success (bool): Indicates if resume generation succeeded.
        execution_error (Optional[str]): Captured error message if generation failed.
        retry_count (int): Current count of retries.
    """

    thread_id: str
    job_description: str
    resume_text: str
    llm_provider: Optional[str]
    template_path: Optional[str]
    extracted_skills: Optional[List[str]]
    suggested_skills: Optional[List[str]]
    approved_skills: Optional[List[str]]
    user_suggestions: Optional[str]
    planner_output: Optional[Dict[str, Any]]
    tailored_context: Optional[Dict[str, Any]]
    generated_resume_path: Optional[str]
    generated_resume_filename: Optional[str]
    ats_score_result: Optional[Dict[str, Any]]
    execution_success: bool
    execution_error: Optional[str]
    retry_count: int